### ISSUE TITLE
Automatically opening new tabs might be blocked.

### ISSUE THREAD

**Issue by siffegh** [hchiam/urlvoid-firefox-extension#1]
Trying it on several sites, works on most but on some  I get "Automatically opening new tabs might be blocked."  How?

**Comment by hchiam** [comment]
This is a known issue. The add-on shows that message to let the user know that it tried but failed, and avoids failing silently by telling the user what they can do instead. 

To fix the problem, I suspect 2 things to investigate next: 

1) Certain websites have a setting that might block the script somehow. For example, I get that problem for https://www.wikipedia.org/ even with noscript marking the page as trusted. 

2) There may be a bug in the code. Nothing shows up in the tab console log. But maybe it shows up in the `devtools-toolbox` (`about:debugging#/runtime/this-firefox` -> "Load Temporary Add-on" -> "Inspect"). 

[UPDATE:]

3) It seems inconsistent. I just tried it on https://www.google.com/ a couple times. One time it worked, one time it failed. Strange.

**Comment by siffegh** [comment]
Thanks, appears to be working everywhere It had been failing before.

**Comment by hchiam** [comment]
Thanks for trying out the add-on @siffegh!
